### PR TITLE
Update code snippet to match describing text

### PR DESCRIPTION
**Pull request by LeeDumond**
The tutorial copy below the the changed line mentions "The code above used the wildcard syntax," but as written it does not. Fixed the line to display correct usage of the wildcard syntax.

### CODE REVIEW

**Comment by Rick-Anderson** [comment]
@spboyer  is this merge conflict something you can quickly fix?

**Comment by Rick-Anderson** [comment]
@LeeDumond  any chance you could resubmit this and I'll merge it before we get a conflict?

**Comment by LeeDumond** [comment]
I can do another pull request on this, no problem

**Comment by LeeDumond** [comment]
Resubmitted.

**Pull request closed without merging**
